# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRV6EBE22WGjjUMJ7VQ-sqTe2V_cmgIk
"""

# Stress and Strain Calculator
print(("Stress and Strain Calculator").center(60))

materials = {
    "1": {"name": "Steel", "yield_strength": 250, "youngs_modulus": 200},
    "2": {"name": "Aluminum", "yield_strength": 95, "youngs_modulus": 69},
    "3": {"name": "Titanium", "yield_strength": 880, "youngs_modulus": 114}
}

while True:
    print()
    print("-" * 60)
    print()

    print("Select a Material:")
    print("1. Steel")
    print("2. Aluminum")
    print("3. Titanium")
    print("4. Custom Material")

    while True:
        choice = input("Enter your choice (1 / 2 / 3 / 4): ")

        if choice in materials:
            material = materials[choice]
            break

        elif choice == "4":
            custom = input("Enter your custom material name: ")

            while True:
                try:
                    yield_strength = float(
                        input("Enter the yield strength (in MPa): ")
                    )

                    if yield_strength > 0:
                        break
                    else:
                        print("Error: Yield strength must be greater than 0.")

                except ValueError:
                    print("Error: Please enter a valid number.")

            while True:
                try:
                    youngs_modulus = float(
                        input("Enter the Young's modulus (in GPa): ")
                    )

                    if youngs_modulus > 0:
                        break
                    else:
                        print("Error: Young's modulus must be greater than 0.")

                except ValueError:
                    print("Error: Please enter a valid number.")

            material = {
                "name": custom,
                "yield_strength": yield_strength,
                "youngs_modulus": youngs_modulus
            }

            break

        else:
            print("Error: Please choose among the available materials.")

    print()
    print(f"Selected Material: {material['name']}")
    print(f"Yield Strength: {material['yield_strength']} MPa")
    print(f"Young's Modulus: {material['youngs_modulus']} GPa")

    while True:
        try:
            force = float(input("Enter the applied force (in newtons): "))
            area = float(input("Enter the area (in square meters): "))
            orig_len = float(
                input("Enter the original length of the material (in meters): ")
            )
            ch_len = float(
                input("Enter the change in length (in meters): ")
            )

            if force < 0:
                print("Error: Force cannot be negative.")
                continue

            elif area <= 0:
                print("Error: Area must be greater than 0.")
                continue

            elif orig_len <= 0:
                print("Error: Original length must be greater than 0.")
                continue

            elif ch_len < 0:
                print("Error: Change in length cannot be negative.")
                continue

            else:
                stress = force / area
                strain = ch_len / orig_len

                # Convert stress from Pa to MPa
                stress_mpa = stress / 1_000_000

                print()
                print(f"Stress = {stress} Pascals (Pa)")
                print(f"Stress = {stress_mpa} MPa")
                print(f"Strain = {strain}")

                factor_of_safety = material["yield_strength"] / stress_mpa

                if factor_of_safety >= 2:
                    print(f"SAFE - Factor of safety: {factor_of_safety:.0f}")

                elif factor_of_safety >= 1:
                    print(f"CAUTION - Factor of safety: {factor_of_safety:.2f}")

                else:
                    print(f"UNSAFE - Factor of safety: {factor_of_safety:.2f}")


                if stress_mpa >= material["yield_strength"]:
                    print("Warning: The material has reached or exceeded its yield strength.")
                else:
                    print("The material is below its yield strength.")

        except ValueError:
            print("Error: Please enter valid characters (numbers only).")
            continue

        break

    while True:
        again = input("\nContinue calculation? (y/n): ")

        if again.lower() == "y":
            break

        elif again.lower() == "n":
            print("Closing program...")
            break

        else:
            print("Invalid input. Please enter 'y' or 'n'.")

    if again.lower() == "n":
        break